# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Publish

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 15
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '15'

    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Set up Apache Maven Central
      uses: actions/setup-java@v2
      with: # running setup-java again overwrites the settings.xml
        distribution: 'adopt'
        java-version: '15'
        server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
        server-username: MAVEN_USERNAME # env variable for username in deploy
        server-password: MAVEN_CENTRAL_TOKEN # env variable for token in deploy
        gpg-private-key: ${{ secrets.MVN_GPG_PRIVATE_KEY }} # Value of the GPG private key to import
        gpg-passphrase: MAVEN_GPG_PASSPHRASE # env variable for GPG private key passphrase

    - name: Publish to Apache Maven Central
      run: mvn deploy -P release
      env:
        MAVEN_USERNAME: ${{ secrets.MVN_SERVER_USERNAME }}
        MAVEN_CENTRAL_TOKEN: ${{ secrets.MVN_SERVER_PASSWORD }}
        MAVEN_GPG_PASSPHRASE: ${{ secrets.MVM_GPG_PASSPHRASE }}
